# Generated by Django 3.1.2 on 2020-10-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_targetgene_validations'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetgene',
            name='both',
            field=models.CharField(default=';', max_length=100),
        ),
    ]
