# Generated by Django 3.1.2 on 2020-10-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_targetgene_both'),
    ]

    operations = [
        migrations.AddField(
            model_name='mirna',
            name='mirgenedb',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
